### PR TITLE
RFC: Refactor of the playbook package

### PR DESCRIPTION
**Pull request by andrioni**
Hi!

I opened this PR in order to propose a small refactor of the playbook package. The idea is make getting the text of the playbook and parsing it more orthogonal, in order to support both new playbook providers (e.g. REST, ZooKeeper, etcd) and different formats (e.g. JSON, TOML).

If you are OK with the changes, I plan to add support for getting the playbooks from a REST interface. The GET request would accept both JSON and YAML, and automatically parse the playbook depending on the Content-Type of the response.

### CODE REVIEW

**Comment by andrioni** [comment]
Also, another possible change in the future (probably not for series of patches) would be to try to load/parse all the queries right after the playbook is loaded: this would help to isolate any provider-related stuff, and could be a bit more stable (e.g. the connection to Consul might not be available during a later step, or the query itself might have changed).

**Comment by alexanderdean** [comment]
Hey @andrioni - on the second point, we have a ticket for that: #22

**Comment by alexanderdean** [comment]
This looks cool to me @andrioni ! I like the approach of refactoring to support multiple discrete back-ends... @jbeemster thoughts when you are back?

**Comment by andrioni** [comment]
Nice! With this and #22, I'll get back to working on a REST interface. Right now I'm thinking about an API pretty identical to the consul one, re-using the `-playbook` and the `-sqlroot` arguments.

**Comment by alexanderdean** [comment]
Sounds good @andrioni ! Thanks for your contributions

**Pull request closed without merging**
