### PR TITLE
Release/0.9.6

### PR DESCRIPTION
**Pull request by colmsnowplow**
Bump to snowflake driver to latest in hopes that it resolves customer issue with odd error message.

Also edited copyright to 2022.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by paulboocock** [comment]
Suggesting that @adatzer reviews this as she bumped the Snowflake driver last time so has some recent knowledge of this and will hopefully remember how it was tested it last time.

**Review by adatzer — APPROVED** [review]
LGTM!
Tested using the snowflake web model both with and without the `-showQueryOutput` option and everything ran as expected.
From the `gosnowflake` release comments, only a note that since [v1.6.2](https://github.com/snowflakedb/gosnowflake/releases/tag/v1.6.2) support for Go 1.15 has been dropped.

**Comment by paulboocock** [comment]
I'd suggest we bump the Github actions to use go 1.17 then.

**Comment by colmsnowplow** [comment]
Good point @adatzer .

I've bumped the go version to 1.17 for the project and the GH actions. I don't think our tests cover whether doing so has any impact on the other targets (eg. if we're using the BQ driver for 1.15) - since 1.15 is no longer supported I think there's some small possibility, however I don't believe there are any breaking changes in the releases so I think we should be ok.

If we think that needs specific attention I can go ahead and manually test before we push release.

**Review by paulboocock — APPROVED** [review]
LGTM. 

I imagine the bump to 1.17 should be safe with the existing libraries. We aren't using particularly old biguqery or aws-sdk-go libraries (~April 2021). Would be good to visit bumping other libraries though, perhaps a 0.9.7, I wouldn't want to block this Snowflake release to test all of that.

**Comment by colmsnowplow** [comment]
Ty! Totally agree on the other dependencies - I gave it a shot to bump them all in one go, and hit some compiler errors. One of those that could be 5 minutes or 5 hours, so I decided to just bump snowflake and prioritise finding out if the driver update makes a difference to the prod issue. 

That issue might turn out to require a follow-up bugfix release, in which case I can spend the time to bump the rest!

**Pull request merged**
