### PR TITLE
Add a random number templating function

### PR DESCRIPTION
**Pull request by tclass**
issue #23

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by alexanderdean** [comment]
CLA not signed yet, pushing back

**Comment by tclass** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @tclass has signed the Individual Contributor License Agreement. Thanks so much

**Comment by BenFradet** [comment]
Thanks merging 👍

**Pull request merged**
